name: ffaa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  forui: ^0.15.1 # shadcn设计语言
  path_provider: ^2.1.1 # 文件路径
  process: ^5.0.0 # 进程
  window_manager: ^0.5.1 # 窗口管理
  hotkey_manager: ^0.2.3 # 快捷键
  tray_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
